---


- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install apache2 and php packages
    apt:
      name:
        -  apache2
        -  libapache2-mod-php
  - name: add php support for apache
    apt:
      name: libapache2-mod-php
